M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date sáb 26 feb 2022 00:15:36
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-26T00:15:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.25Y-3.2
T0
M30
