; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	https://github.com/StuartsProjects/SX12XX-LoRa.git
	https://github.com/ESP32Async/ESPAsyncWebServer
	ArduinoJson
	https://github.com/cmumme/ESP32Servo.git

extra_scripts =
    merge-bin.py

board_build.partitions = partitions.csv
upload_port = COM8